# -*- coding: utf-8 -*-
"""project-I.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hssWo5p9arxfomW82UjbvcBPGaI2v_Cg
"""

import pandas as pd
df = pd.read_csv("/content/IRIS.csv")
df

df.head()

df.tail()

df.info()

df.describe()

df.columns

df.shape

df.duplicated().sum()

print("removing duplicates")
print(df.duplicated().sum())
print(df.drop_duplicates())
print()

df.shape

df.isnull().sum()

df.shape

import seaborn as sns
import matplotlib.pyplot as plt

df.species.value_counts(normalize = True)

df.species.value_counts().plot(kind = "bar")
plt.title ("Value Count of the Species")
plt.xlabel ("Species")
plt.ylabel ("Count")
plt.xticks(rotation=0)
plt.show()

#Countplot

sns.countplot(x= 'species' , data =df)
plt.xlabel('Species')
plt.ylabel('Count')
plt.title("Distribution of Iris Species")
plt.show()

#Box Plot

sns.boxplot(x='species', y = 'sepal_length' , data=df)
plt.xlabel('Species')
plt.ylabel('Sepal Length')
plt.title("Box Plot of Sepal Length by Species")
plt.show()

sns.boxplot(x='species', y = 'sepal_width' , data=df)
plt.xlabel('Species')
plt.ylabel('sepal_width')
plt.title("Box Plot of sepal_width by Species")
plt.show()

sns.boxplot(x='species', y = 'petal_length' , data=df)
plt.xlabel('Species')
plt.ylabel('Petal Length')
plt.title("Box Plot of Petal Length by Species")
plt.show()

sns.boxplot(x='species', y = 'petal_width' , data=df)
plt.xlabel('Species')
plt.ylabel('Petal Width')
plt.title("Box Plot of Petal Width by Species")
plt.show()

#Pair Plot

sns.pairplot(df, hue = "species")
plt.title("Pair Plot of Iris Dataset")
plt.show()

df.corr()

correlation_matrix = df.corr()
sns.heatmap(correlation_matrix , annot = True, cmap = 'Pastel1')
plt.title("Correlation Matrix of Iris Dataset")
plt.show()

plt.figure(figsize = (20,5))
sns.countplot(x='sepal_length' , data=df)
plt.xlabel('Sepal Length')
plt.title("Count Plot of Sepal Length")
plt.show()